### ISSUE TITLE
POST request at api/play requests integer instead of String (ENUM)

### ISSUE THREAD

**Issue by techcoachralph** [Chaos-Camp/RockPaperScissorsChallenge#1]
### Summary:
According to the README.md (which differs in the Swagger documentation), we should be passing a string or ENUM into the POST request to /api/play but it is requiring an integer instead

### Expected Results:
I should be able to pass the string or ENUM for “ROCK”, “PAPER” or “SCISSOR” (as well as the integer) and be returned the PlayResponse
Status code: 200
```
{
	"your_weapon": "ROCK",
	"computer_weapon": "ROCK",
	"winner": "DRAW"
}
```

### Actual Results:
When I pass the string to the endpoint, I am returned an error message:
Status Code: 422
```
{
	"detail": [
		{
			"type": "int_parsing",
			"loc": [
				"body",
				"choice"
			],
			"msg": "Input should be a valid integer, unable to parse string as an integer",
			"input": "ROCK",
			"url": "https://errors.pydantic.dev/2.4/v/int_parsing"
		}
	]
}
```

### Steps to Reproduce:
Send POST request to endpoint: http://localhost:8080/api/play with request body:
```
{
    "choice": "ROCK"
}
```

### Screenshots:
![Screenshot 2023-11-13 at 8 04 40 AM](https://github.com/Chaos-Camp/RockPaperScissorsChallenge/assets/136257561/0ba384b8-9e8c-4fdd-b43f-bc57561390e2)

### Environments:
Local docker build per instructions

### Note:
While the Swagger documentation says that you should be using the integer, the README says that it should be the string (ENUM) of the weapon. From a customer and quality, ease of use perspective, I would recommend that we use the string (ENUM), even if using the integer is still an option. The customer will not necessarily remember which integer is assigned to which weapon.

**Comment by copyleftdev** [comment]
@techcoachralph  I added code that allows enum to handle both integer an string

**Comment by techcoachralph** [comment]
Tested and validated that this resolved. Recieved 200 status code and correct response body after submitting string of weapon.
